# Generated by Django 4.2.16 on 2024-11-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['-time_create', 'word']},
        ),
        migrations.AlterField(
            model_name='word',
            name='example',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
