# Generated by Django 4.2.16 on 2024-11-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0004_alter_word_user_wordgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordgroup',
            name='is_main',
            field=models.BooleanField(blank=True, null=True, verbose_name='main'),
        ),
    ]
