# Generated by Django 4.2.16 on 2024-11-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0005_wordgroup_is_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordgroup',
            name='is_main',
            field=models.BooleanField(verbose_name='main'),
        ),
    ]
