# Generated by Django 4.2.16 on 2024-11-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0008_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='show_recent_words',
            field=models.BooleanField(default=True),
        ),
    ]
