# Generated by Django 4.2.16 on 2024-11-17 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0009_userprofile_show_recent_words'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='show_recent_words',
        ),
    ]
