# Generated by Django 4.2.16 on 2024-11-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0010_remove_userprofile_show_recent_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='what_type_show',
            field=models.CharField(choices=[('fav', 'Favourite'), ('learn', 'Learning')], default='learn', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='words_num_in_prof',
            field=models.IntegerField(choices=[(5, '5'), (3, '3'), (1, '1'), (0, '0')], default=5),
        ),
    ]
