# Generated by Django 4.2.16 on 2024-11-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0011_userprofile_what_type_show_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
