# Generated by Django 4.2.16 on 2024-11-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0014_alter_word_is_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='access_dictionary',
            field=models.CharField(choices=[('every', 'Everybody'), ('friends', 'Friends'), ('only', 'Only me')], default='every', max_length=10),
        ),
    ]
