# Generated by Django 5.1.3 on 2024-12-10 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0016_friendship'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('time_to_read', models.IntegerField()),
                ('word_count', models.IntegerField()),
            ],
            options={
                'ordering': ['title'],
                'indexes': [models.Index(fields=['title'], name='med_reading_title_5f67c1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReadingEnglishWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='med.readingtext')),
            ],
            options={
                'ordering': ['word'],
            },
        ),
        migrations.CreateModel(
            name='ReadingTranslatedWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.CharField(blank=True, max_length=100, null=True)),
                ('word', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='med.readingenglishwords')),
            ],
        ),
        migrations.AddIndex(
            model_name='readingenglishwords',
            index=models.Index(fields=['word'], name='med_reading_word_a03fde_idx'),
        ),
    ]
