# Generated by Django 5.1.3 on 2024-12-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0017_readingtext_readingenglishwords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingtext',
            name='eng_level',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2, null=True),
        ),
    ]
