# Generated by Django 5.1.3 on 2024-12-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0018_readingtext_eng_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingenglishwords',
            name='text',
        ),
        migrations.RemoveField(
            model_name='readingtranslatedwords',
            name='word',
        ),
        migrations.AlterModelOptions(
            name='readingtext',
            options={'ordering': ['eng_level', 'title']},
        ),
        migrations.RemoveIndex(
            model_name='readingtext',
            name='med_reading_title_5f67c1_idx',
        ),
        migrations.AddField(
            model_name='readingtext',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='readingtext',
            name='words_with_translations',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='readingtext',
            name='eng_level',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2),
        ),
        migrations.AddIndex(
            model_name='readingtext',
            index=models.Index(fields=['eng_level', 'title'], name='med_reading_eng_lev_074308_idx'),
        ),
        migrations.DeleteModel(
            name='ReadingEnglishWords',
        ),
        migrations.DeleteModel(
            name='ReadingTranslatedWords',
        ),
    ]
