# Generated by Django 5.1.3 on 2024-12-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0019_remove_readingenglishwords_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingtext',
            name='auth',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
