# Generated by Django 5.1.3 on 2024-12-13 12:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0021_readingtext_is_auth_a'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readingtext',
            options={'ordering': ['eng_level', 'word_count', 'title']},
        ),
        migrations.AddField(
            model_name='wordgroup',
            name='uses_users',
            field=models.ManyToManyField(blank=True, related_name='uses_of_group', to=settings.AUTH_USER_MODEL),
        ),
    ]
