# Generated by Django 5.1.3 on 2024-12-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0022_alter_readingtext_options_wordgroup_uses_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='word_type',
            field=models.CharField(choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb'), ('pronoun', 'Pronoun'), ('phrasal verb', 'Phrasal verb'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='readingtext',
            name='eng_level',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='A1', max_length=2),
        ),
    ]
