# Generated by Django 5.1.3 on 2024-12-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0023_word_word_type_alter_readingtext_eng_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='show_word_stats',
            field=models.CharField(choices=[('every', 'Everybody'), ('friends', 'Friends'), ('only', 'Only me')], default='every', max_length=10),
        ),
    ]
