# Generated by Django 5.1.3 on 2024-12-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0024_userprofile_show_word_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='show_bar_chart',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_line_chart',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_pie_chart',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='show_word_stats',
            field=models.CharField(choices=[('every', 'Everybody'), ('friends', 'Friends'), ('only', 'Only me'), ('nobody', 'Nobody')], default='every', max_length=10),
        ),
    ]
