# Generated by Django 5.1.3 on 2025-01-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0027_achievement_userprofile_edited_words_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userachievement',
            name='custom_order',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='is_chenged',
            field=models.BooleanField(default=False),
        ),
    ]
