# Generated by Django 5.1.3 on 2025-01-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0028_userprofile_achicment_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='requirements',
            field=models.TextField(blank=True),
        ),
    ]
