# Generated by Django 5.1.3 on 2025-01-05 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0029_achievement_requirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='СommunityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('added', 'Added')], default='public', max_length=20)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='med.wordgroup')),
            ],
            options={
                'ordering': ['group__name'],
                'indexes': [models.Index(fields=['group'], name='med_сommuni_group_i_7216d1_idx')],
            },
        ),
    ]
