# Generated by Django 5.1.3 on 2025-01-05 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0030_сommunitygroup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='СommunityGroup',
            new_name='CommunityGroup',
        ),
        migrations.RenameIndex(
            model_name='communitygroup',
            new_name='med_communi_group_i_2f27e8_idx',
            old_name='med_сommuni_group_i_7216d1_idx',
        ),
    ]
