# Generated by Django 5.1.3 on 2025-03-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0033_category_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hide_warning_message',
            field=models.BooleanField(default=False),
        ),
    ]
