# Generated by Django 5.1.3 on 2025-05-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0037_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('1', 'Base'), ('2', 'Group_r')], default='1', max_length=20),
        ),
    ]
