# Generated by Django 5.1.3 on 2025-08-20 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0040_initial_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitygroup',
            name='group',
        ),
        migrations.DeleteModel(
            name='ReadingText',
        ),
        migrations.DeleteModel(
            name='CommunityGroup',
        ),
    ]
