# Generated by Django 5.1.3 on 2025-08-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
        ('med', '0041_remove_communitygroup_group_delete_readingtext_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordgroup',
            name='words',
            field=models.ManyToManyField(blank=True, to='dictionary.word'),
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
