# Generated by Django 5.1.3 on 2025-08-20 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_wordgroup'),
        ('med', '0042_alter_wordgroup_words_delete_word'),
        ('practice', '0002_alter_communitygroup_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.wordgroup'),
        ),
        migrations.DeleteModel(
            name='WordGroup',
        ),
    ]
