# Generated by Django 5.1.3 on 2025-08-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0043_alter_notification_group_delete_wordgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='grouper',
            field=models.BooleanField(default=False),
        ),
    ]
