# Generated by Django 5.1.3 on 2025-08-21 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0043_userprofile_grouper'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
