# Generated by Django 5.1.3 on 2025-08-21 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0045_userstreak'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userachievement',
            name='achievement',
        ),
        migrations.RemoveField(
            model_name='userachievement',
            name='user',
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
        migrations.DeleteModel(
            name='UserAchievement',
        ),
    ]
