# Generated by Django 5.1.3 on 2025-08-21 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0046_remove_userachievement_achievement_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
