# Generated by Django 5.1.3 on 2025-08-22 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0047_delete_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='chenged_order',
            new_name='changed_order',
        ),
    ]
