# Generated by Django 5.1.3 on 2025-12-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0048_rename_chenged_order_userprofile_changed_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_bot_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
