# Generated by Django 5.1.3 on 2025-08-20 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('med', '0041_remove_communitygroup_group_delete_readingtext_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('time_to_read', models.IntegerField()),
                ('word_count', models.IntegerField()),
                ('eng_level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='A1', max_length=2)),
                ('content', models.TextField(blank=True)),
                ('words_with_translations', models.JSONField(blank=True, default=dict, null=True)),
                ('auth', models.CharField(blank=True, max_length=200)),
                ('is_auth_a', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['eng_level', 'word_count', 'title'],
                'indexes': [models.Index(fields=['eng_level', 'title'], name='practice_re_eng_lev_a525b0_idx')],
            },
        ),
        migrations.CreateModel(
            name='CommunityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('added', 'Added')], default='public', max_length=20)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='med.wordgroup')),
            ],
            options={
                'ordering': ['group__name'],
                'indexes': [models.Index(fields=['group'], name='practice_co_group_i_db4c78_idx')],
            },
        ),
    ]
