# Generated by Django 5.1.3 on 2025-08-20 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_wordgroup'),
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitygroup',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dictionary.wordgroup'),
        ),
    ]
