# Generated by Django 5.1.3 on 2025-08-20 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WordGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_main', models.BooleanField(default=False, verbose_name='main')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('uses_users', models.ManyToManyField(blank=True, related_name='uses_of_group', to=settings.AUTH_USER_MODEL)),
                ('words', models.ManyToManyField(blank=True, to='dictionary.word')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='dictionary__name_db9f47_idx')],
            },
        ),
    ]
