# Generated by Django 5.1.3 on 2026-01-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_wordgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='example',
            field=models.TextField(blank=True, null=True),
        ),
    ]
