# Generated by Django 5.1.3 on 2025-08-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('1', 'Base'), ('2', 'Group_r'), ('3', 'Friend_r')], default='1', max_length=20),
        ),
    ]
